name = "ChebyshevCircles"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ChebyshevCircles"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "doc-gen4"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[lean_lib]]
name = "ChebyshevCircles"

# Enable documentation generation
[package.meta.doc]
buildCommand = "lake build :docgen"
